# Generated by Django 5.0.6 on 2024-06-28 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=15)),
                ('mac_address', models.CharField(max_length=17)),
                ('device_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('firmware_version', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.CharField(max_length=10)),
                ('speed', models.CharField(max_length=50)),
                ('vlan', models.CharField(max_length=50)),
                ('connected_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_ports', to='devices.device')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='devices.device')),
            ],
        ),
    ]
