# Generated by Django 5.0.6 on 2024-06-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('computers', 'Computers'), ('servers', 'Servers'), ('networking equipment', 'Networking Equipment')], max_length=100)),
                ('status', models.CharField(choices=[('in_use', 'In Use'), ('in_storage', 'In Storage'), ('under_maintenance', 'Under Maintenance')], default='in_storage', max_length=20)),
                ('status_history', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hardware_items',
            },
        ),
    ]
